# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
